Revert "Update github-pages gem to 178"
This reverts commit 80bc84fed33c67fb2686dc097386ee648c1dac61.

```shell
$ bundle exec jekyll serve
[...]
bundler: failed to load command: jekyll (/home/chet/.gem/ruby/2.5.0/bin/jekyll)
FrozenError: can't modify frozen String
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-relative-links-0.5.2/lib/jekyll-relative-links/generator.rb:47:in `gsub!'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-relative-links-0.5.2/lib/jekyll-relative-links/generator.rb:47:in `replace_relative_links!'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-relative-links-0.5.2/lib/jekyll-relative-links/generator.rb:39:in `block in generate'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-relative-links-0.5.2/lib/jekyll-relative-links/generator.rb:36:in `each'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-relative-links-0.5.2/lib/jekyll-relative-links/generator.rb:36:in `generate'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:176:in `block in generate'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `each'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `generate
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `each'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `generate'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:72:in `process'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
  /home/chet/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/chet/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/chet/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/chet/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/chet/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/chet/.gem/ruby/2.5.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
  /home/chet/.gem/ruby/2.5.0/bin/jekyll:23:in `load'
  /home/chet/.gem/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
```